services:
    Sidus\EAVPermissionBundle\Form\AttributePermissionFormHandler:
        decorates: Sidus\EAVModelBundle\Form\AttributeFormBuilderInterface
        arguments:
            - '@Sidus\EAVPermissionBundle\Form\AttributePermissionFormHandler.inner'
            - '@Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface'
