services:
    Sidus\EAVPermissionBundle\Voter\AttributeVoter:
        arguments:
            - '@Symfony\Component\Security\Core\Authorization\AccessDecisionManagerInterface'
        tags:
            - { name: security.voter }

    Sidus\EAVPermissionBundle\Voter\FamilyVoter:
        arguments:
            - '@Symfony\Component\Security\Core\Authorization\AccessDecisionManagerInterface'
        tags:
            - { name: security.voter }

    Sidus\EAVPermissionBundle\Voter\EAVDataVoter:
        arguments:
            - '@Sidus\EAVPermissionBundle\Voter\FamilyVoter'
        tags:
            - { name: security.voter }
